/**
 * Add Product Variant Use Case
 *
 * Creates a new variant for a product.
 * Validates SKU uniqueness and product existence.
 */

import { ProductVariantRepositoryInterface } from "@/domain/interfaces/repositories/product-variant.repository.interface";
import { ProductRepositoryInterface } from "@/domain/interfaces/repositories/product.repository.interface";
import { ProductVariantEntity } from "@/domain/entities/product-variant.entity";
import { ProductNotFoundException } from "@/domain/exceptions/product-not-found.exception";

export interface AddProductVariantInput {
  productId: string;
  sku: string;
  size?: string | null;
  color?: string | null;
  stockQuantity?: number;
  priceAdjustment?: number;
  isAvailable?: boolean;
}

export interface AddProductVariantOutput {
  id: string;
  productId: string;
  sku: string;
  size: string | null;
  color: string | null;
  stockQuantity: number;
  priceAdjustment: number;
  isAvailable: boolean;
}

export class AddProductVariantUseCase {
  constructor(
    private readonly variantRepository: ProductVariantRepositoryInterface,
    private readonly productRepository: ProductRepositoryInterface
  ) {}

  async execute(
    input: AddProductVariantInput
  ): Promise<AddProductVariantOutput> {
    // Verify product exists
    const product = await this.productRepository.findById(input.productId);
    if (!product) {
      throw new ProductNotFoundException(input.productId);
    }

    // Check SKU uniqueness
    const existingSku = await this.variantRepository.existsBySku(input.sku);
    if (existingSku) {
      throw new Error(`SKU "${input.sku}" already exists`);
    }

    // Create the variant entity
    const variant = new ProductVariantEntity(
      "", // ID will be generated by database
      input.productId,
      input.sku,
      input.size ?? null,
      input.color ?? null,
      input.stockQuantity ?? 0,
      input.priceAdjustment ?? 0,
      input.isAvailable ?? true,
      new Date(),
      new Date()
    );

    // Save to database
    const saved = await this.variantRepository.create(variant);

    return {
      id: saved.id,
      productId: saved.productId,
      sku: saved.sku,
      size: saved.size,
      color: saved.color,
      stockQuantity: saved.stockQuantity,
      priceAdjustment: saved.priceAdjustment,
      isAvailable: saved.isAvailable,
    };
  }
}
